name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: "go.work"
          cache: true

      - name: Dead code analysis server
        run: go run golang.org/x/tools/cmd/deadcode@latest -test .
        working-directory: ./tunnel-server

      - name: Dead code analysis cli
        run: go run golang.org/x/tools/cmd/deadcode@latest -test ./cmd/iskndr
        working-directory: ./iskndr

      - name: golangci-lint server
        uses: golangci/golangci-lint-action@v8
        with:
          working-directory: ./tunnel-server

      - name: golangci-lint cli
        uses: golangci/golangci-lint-action@v8
        with:
          working-directory: ./iskndr

      - name: Test shared module
        working-directory: ./shared
        run: |
          go test -v -race ./...

      - name: Test tunnel-server
        working-directory: ./tunnel-server
        run: |
          go test -v -race ./...

      - name: Test iskndr CLI
        working-directory: ./iskndr
        run: |
          go test -v -race ./...

      - name: Build tunnel-server
        working-directory: ./tunnel-server
        run: |
          go build -v .

      - name: Build iskndr CLI
        working-directory: ./iskndr
        run: |
          go build -v ./cmd/iskndr
